language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t aksharkay/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aksharkay/react-test npm test -- --coverage

after_success:
  - docker build -t aksharkay/multi-client ./client
  - docker build -t aksharkay/multi-nginx ./nginx
  - docker build -t aksharkay/multi-server ./server
  - docker build -t aksharkay/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push aksharkay/multi-client
  - docker push aksharkay/multi-nginx
  - docker push aksharkay/multi-server
  - docker push aksharkay/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'multi-docker'
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-523067638276'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY